services:
  master:
    image: locustio/locust:master
    container_name: master
    ports:
      - "8089:8089"
    volumes:
      - ./mlocust:/home/locust
    environment:
      - TZ=${TZ:-Asia/Seoul}
      - CLUSTER_URL=${CLUSTER_URL:-mongodb://host.docker.internal:27017}
      - DB_NAME=${DB_NAME:-loadtest}
      - COLLECTION_NAME=${COLLECTION_NAME:-rwcoll}
      - COLLECTION_SCAN=${COLLECTION_SCAN:-scancoll}
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "pip install -r requirements.txt && locust -f envcheck.py --master",
      ]

  worker:
    image: locustio/locust:master
    volumes:
      - ./mlocust:/home/locust
    environment:
      - TZ=${TZ:-Asia/Seoul}
      - CLUSTER_URL=${CLUSTER_URL:-mongodb://host.docker.internal:27017}
      - DB_NAME=${DB_NAME:-loadtest}
      - COLLECTION_NAME=${COLLECTION_NAME:-rwcoll}
      - COLLECTION_SCAN=${COLLECTION_SCAN:-scancoll}
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "pip install -r requirements.txt && locust -f envcheck.py --worker --master-host=master",
      ]
